export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUESTED"
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"

export const SET_CATEGORY_ID = "SET_CATEGORY_ID"

export const FETCH_CART_REQUEST = "FETCH_CART_REQUESTED"
export const FETCH_CART_FAILURE = "FETCH_CART_FAILURE"
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS"

export const ADD_CART = "FETCH_CART_REQUESTED"
export const UPDATE_CART = "FETCH_CART_FAILURE"
export const REMOVE_CART = "FETCH_CART_SUCCESS"

export const ADD_USER = "ADD_USER"
export const REMOVE_USER = "REMOVE_USER"

